Repository PrintMakerLab/mks-wifi-plugin, pull requests merged in 2021-02, with the labels that each got.

#100 MWP-99 Button alignment
  i18n/mksplugin.pot
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.po
  qml/MonitorItem4x.qml
Labels: enhancement

#97 CPR-97 Add translation of Simplify Chinese.
  i18n/ru_SimplifiedChinese/LC_MESSAGES/mksplugin.mo
  i18n/ru_SimplifiedChinese/mksplugin.po
Labels: enhancement

#101 MWP-98 Add Chinese language
  i18n/zh_CN/LC_MESSAGES/mksplugin.mo
  i18n/zh_CN/mksplugin.po
  plugin.json
Labels: enhancement

#102 MWP-96 Italian locale added.
  i18n/it_IT/LC_MESSAGES/mksplugin.mo
  i18n/it_IT/mksplugin.po
Labels: enhancement

#103 MWP-95 Cura Arachne_engine_alpha fix
  __init__.py
Labels: bug

#104 Readme enhancement
  README.md
Labels: documentation, enhancement

#106 MWP-11 Model image fix
  MKSOutputDevice.py
  MachineConfig.py
  SaveOutputDevice.py
  i18n/it_IT/LC_MESSAGES/mksplugin.mo
  i18n/it_IT/mksplugin.po
  i18n/mksplugin.pot
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.po
  i18n/zh_CN/LC_MESSAGES/mksplugin.mo
  i18n/zh_CN/mksplugin.po
  qml/MachineConfig.qml
  qml/MonitorItem4x.qml
  utils.py
Labels: bug, enhancement

#109 MWP-108 Scale fix
  qml/MachineConfig.qml
  qml/MonitorItem4x.qml
Labels: bug

#112 MWP-111 Translation fix
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.po
Labels: bug

#119 MWP-114 Extension fix for file upload
  MKSOutputDevice.py
  i18n/it_IT/mksplugin.po
  i18n/mksplugin.pot
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.po
  i18n/zh_CN/mksplugin.po
Labels: bug

#121 MWP-120 Obsolete translation fix
  MKSOutputDevice.py
Labels: enhancement

#118 MWP-116 Reworked dialogs with filenames.
  MKSDialog.py
  MKSOutputDevice.py
Labels: bug

#124 MWP-123 on_read cognitive complexity
  MKSOutputDevice.py
Labels: enhancement

#126 MWP-125 Time fixes
  MKSOutputDevice.py
Labels: enhancement
