Repository PrintMakerLab/mks-wifi-plugin, pull requests merged in 2022-01, with the labels that each got.

#257 [MWP-58] Plugin functions rewritten
  Constants.py
  MKSOutputDevice.py
  MKSOutputDevicePlugin.py
  MKSPreview.py
  MachineConfig.py
  i18n/mksplugin.pot
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.po
  qml/MachineConfig.qml
Labels: bug

#262 [CPR] Add Auto File Renaming feature
  Constants.py
  MKSOutputDevice.py
  MachineConfig.py
  i18n/mksplugin.pot
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.mo
  i18n/ru_RU/mksplugin.po
  qml/MachineConfig.qml
  tests/__init__.py
  tests/test_utils.py
  utils.py
Labels: feature

#264 [MWP-248] Add codeowners file
  .github/CODEOWNERS
  .github/release-drafter.yml
Labels: type: maintenance

#265 [DEV] Release 1.3.0
  plugin.json
Labels: [DEV], skip-changelog

#267 [MWP-266] Add "type: community" label to the versioning
  .github/release-drafter.yml
Labels: type: maintenance

#268 [MWP-266] Update release template
  .github/release-drafter.yml
Labels: skip-changelog
