Repository PrintMakerLab/mks-wifi-plugin, pull requests merged in 2022-11, with the labels that each got.

#355 [MWP-353] Cyrrilic filename rename
  MKSOutputDevice.py
  utils.py
Labels: type: feature-minor

#356 [MWP-286] Delete/print file fix
  MKSOutputDevice.py
Labels: type: bug

#360 [MWP-358] Drive prefix feature added
  MKSOutputDevice.py
  i18n/de_DE/mksplugin.po
  i18n/es_ES/mksplugin.po
  i18n/it_IT/LC_MESSAGES/mksplugin.mo
  i18n/it_IT/mksplugin.po
  i18n/mksplugin.pot
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.po
  i18n/zh_CN/LC_MESSAGES/mksplugin.mo
  i18n/zh_CN/mksplugin.po
  qml/MonitorItem.qml
Labels: type: feature-minor

#362 [DEV] Release 1.4.2
  plugin.json
Labels: skip-changelog

#363 [DEV] Release 1.4.3-dev
  plugin.json
Labels: skip-changelog
