Repository PrintMakerLab/mks-wifi-plugin, pull requests merged in 2022-05, with the labels that each got.

#290 Fix the infinite connect / disconnect loop
  MKSOutputDevice.py
Labels: type: community

#288 Qt6 migration
  MKSDialog.py
  MKSOutputDevice.py
  MKSOutputDevicePlugin.py
  MKSPreview.py
  MachineConfig.py
  __init__.py
  plugin.json
  qml/MKSConnectBtn.qml
  qml/MachineConfig.qml
  qml/MonitorItem.qml
Labels: type: community

#292 Qt6 migration - pt2
  qml/MKSConnectBtn.qml
  qml/MonitorItem.qml
Labels: type: community

#293 [MWP-287] Support new Cura 5.0 updates
  MKSOutputDevice.py
  MKSPreview.py
  qml/MachineConfig.qml
  qml/MonitorItem.qml
Labels: type: dependencies

#304 [MWP-302] Translation autogen
  .github/workflows/i18n_updater.yml
  .github/workflows/mo_updater.yml
  i18n/de_DE/mksplugin.po
  i18n/it_IT/LC_MESSAGES/mksplugin.mo
  i18n/it_IT/mksplugin.po
  i18n/mksplugin.pot
  i18n/ru_RU/LC_MESSAGES/mksplugin.mo
  i18n/ru_RU/mksplugin.po
  i18n/zh_CN/LC_MESSAGES/mksplugin.mo
  i18n/zh_CN/mksplugin.po
Labels: type: feature

#306 [MWP-301] Visual fixes
  qml/MachineConfig.qml
Labels: bug, type: bug

#307 Add .curapackage support
  .github/workflows/create_release_with_packages.yml
  .github/workflows/package.json
Labels: type: maintenance

#310 [MWP-271] Reset old settings after plugin updated
  MKSOutputDevicePlugin.py
Labels: type: bug

#312 [DEV] Release 1.4.0
  plugin.json
Labels: [DEV], skip-changelog

#313 [DEV] Release 1.4.1-dev
  plugin.json
Labels: [DEV], skip-changelog
