Repository PrintMakerLab/mks-wifi-plugin, pull requests merged in 2022-07, with the labels that each got.

#325 [MWP-309] Translation workflow with PR
  .github/workflows/i18n_updater.yml
  .github/workflows/mo_updater.yml
  .github/workflows/translation.yml
Labels: type: maintenance

#324 Add es_ES locale
  i18n/es_ES/mksplugin.po
Labels: type: community

#327 [MWP-322] Update feature labels for versioning
  .github/release-drafter.yml
Labels: type: maintenance

#329 [MWP-328] Fix sonarqube code smells
  .sonarcloud.properties
  MKSOutputDevicePlugin.py
  __init__.py
Labels: type: maintenance

#333 [MWP-332] Support the 8.1.0 version of SDK for Cura 5.1+
  plugin.json
Labels: type: dependencies

#335 [DEV] Release 1.4.2-dev
  plugin.json
Labels: [DEV], skip-changelog

#338 [MWP-337] Issue templates fixes
  .github/ISSUE_TEMPLATE/bugreport.yaml
  .github/ISSUE_TEMPLATE/featurerequest.yaml
Labels: type: maintenance

#339 [MWP-337] Quickfix
  .github/ISSUE_TEMPLATE/bugreport.yaml
Labels: skip-changelog

#342 [MWP-341] Printer reboot while print starts fix
  MKSPreview.py
Labels: type: bug
